# Reference only: for documentation purposes.
# The actual config is rendered from proxy_config in litellm-values.yaml into a ConfigMap.
# Secrets (master_key, api_key) are provided as environment variables via Vault Agent.

general_settings:
  # References PROXY_MASTER_KEY environment variable exported by Vault Agent
  master_key: os.environ/PROXY_MASTER_KEY

litellm_settings:
  drop_params: true
  success_callback:
    - "stdout"

model_list:
  - model_name: openai-gpt-4
    litellm_params:
      model: openrouter/openai/gpt-4
      api_base: https://openrouter.ai/api/v1
      api_key: os.environ/OPENROUTER_API_KEY
  - model_name: claude-3-opus
    litellm_params:
      model: openrouter/anthropic/claude-3-opus
      api_base: https://openrouter.ai/api/v1
      api_key: os.environ/OPENROUTER_API_KEY
